# -*- coding: utf-8 -*-
"""ML_ASS_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grIYCDAXxctYFzy2eHEUch6G6Ugy7wrX
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("https://raw.githubusercontent.com/yuvraj1160/ML-_Prac_1/refs/heads/main/adult.csv")

display(df.head(10))
display(df.tail(10))

df.info()
display(df.describe())

display(df.isnull().sum())

df.replace('?', np.nan, inplace=True)
df.replace(' ?', np.nan, inplace=True)

for col in df.columns:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].mode()[0], inplace=True)

print("Missing values after handling:\n\n", df.isnull().sum())

#convert category data into numeric data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

cat_cols = df.select_dtypes(include=['object']).columns

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

display(df.head())

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X = df.drop('income', axis=1)
y = df['income']

X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

print("Scaled Features Dataset:")
display(X_scaled.head())

from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(X_scaled, y, test_size=0.30, random_state=42)

X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.50, random_state=42)

print("Original Dataset Shape:", X_scaled.shape, y.shape,"\n")
print("Training Dataset (70%) Shape:", X_train.shape, y_train.shape,"\n")
print("Validation Dataset (15%) Shape:", X_val.shape, y_val.shape,"\n")
print("Testing Dataset (15%) Shape:", X_test.shape, y_test.shape,"\n")

from sklearn.feature_selection import SelectKBest, f_classif

print("Correlation Matrix Results ---")
train_data = X_train.copy()
train_data['income'] = y_train.values
corr_matrix = train_data.corr()

corr_target = abs(corr_matrix['income']).sort_values(ascending=False)
print("Top 5 features based on Correlation:\n", corr_target[1:6])

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm')
plt.title("Correlation Matrix of Training Features")
plt.show()


print("\nSelectKBest Results ---")

selector = SelectKBest(score_func=f_classif, k=5)
selector.fit(X_train, y_train)

feature_scores = pd.DataFrame({'Feature': X_train.columns, 'Score': selector.scores_})
feature_scores = feature_scores.sort_values(by='Score', ascending=False)

print("Top 5 features based on SelectKBest:\n", feature_scores.head(5))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Before Preprocessing (Original Scale)
sns.histplot(df['age'], kde=True, ax=axes[0], color='skyblue', bins=30)
axes[0].set_title("Before Preprocessing (Original Scale)")
axes[0].set_xlabel("Age")
axes[0].set_ylabel("Frequency")

# After Preprocessing (Scaled )
sns.histplot(X_scaled['age'], kde=True, ax=axes[1], color='lightgreen', bins=30)
axes[1].set_title("After Preprocessing (Standard Scaled)")
axes[1].set_xlabel("Age (Scaled)")
axes[1].set_ylabel("Frequency")

plt.tight_layout()
plt.show()

df.to_csv("preprocessed_dataset.csv", index=False)

"""#Submitted By: Yuvraj Singh | Roll No: BETN1AI25123

###Conclusion:
In this lab evaluation, the Adult Income dataset was successfully cleaned and prepared for Machine Learning. Missing values ('?') were handled using the mode, and categorical features were encoded into numeric values via LabelEncoder. StandardScaler was then applied to normalize feature ranges, significantly improving overall data quality. Following this, the dataset was partitioned into Training (70%), Validation (15%), and Testing (15%) subsets for unbiased evaluation. Finally, Feature Selection techniques (Correlation Matrix and SelectKBest) identified key demographic attributes like age, education, and capital gains as the most important income predictors. These preprocessing steps successfully transformed the raw dataset into a standardized and optimized format ready for accurate model training.
"""

